r"""Bootstrap of the parameter uncertainty of a nowcast (innovation I5).

The Kalman smoother delivers the predictive variance of the nowcast *given* the
estimated parameters :math:`\hat\theta`. To account for the estimation error the
parameters are bootstrapped (Stoffer & Wall, 1991; Pfeffermann & Tiller, 2005;
Rodríguez & Ruiz, 2012):

1. draw a pseudo-panel :math:`X^{*}_b` with the missing-data pattern of the original
   panel, either

   * ``method="parametric"`` - simulated from the fitted state-space model
     (:math:`\alpha_{t+1} = T\alpha_t + R\eta_t`, :math:`x_t = Z\alpha_t + \varepsilon_t`;
     for the two-step model the target is generated by the fitted bridge equation
     :math:`y^Q_t = \hat\alpha + \hat\beta'\bar f^Q_t + \hat\sigma_e e_t`), or
   * ``method="block"`` - a moving-block bootstrap of whole target periods (Künsch,
     1989), model-free and available for every estimator;

2. re-estimate the model on :math:`X^{*}_b`, giving :math:`\hat\theta^{*}_b`;
3. run the smoother with :math:`\hat\theta^{*}_b` **on the original data**, giving the
   nowcast :math:`\hat y_t(\hat\theta^{*}_b)` and its smoothing standard deviation
   :math:`s_t(\hat\theta^{*}_b)`.

The spread of :math:`\hat y_t(\hat\theta^{*}_b)` across replications measures the
parameter uncertainty; :func:`nowcastbox.density.nowcast_distribution` combines both
sources into a Gaussian mixture.

Replications use independent child seeds of :class:`numpy.random.SeedSequence`, so the
draws do not depend on ``n_jobs``.

References
----------
Stoffer, D. S. & Wall, K. D. (1991). Bootstrapping state-space models: Gaussian maximum
likelihood estimation and the Kalman filter. *JASA*, 86(416), 1024-1033.

Pfeffermann, D. & Tiller, R. (2005). Bootstrap approximation to prediction MSE for
state-space models with estimated parameters. *Journal of Time Series Analysis*,
26(6), 893-916.

Rodríguez, A. & Ruiz, E. (2012). Bootstrap prediction mean squared errors of
unobserved states based on the Kalman filter with estimated parameters.
*Computational Statistics & Data Analysis*, 56(1), 62-74.

Künsch, H. R. (1989). The jackknife and the bootstrap for general stationary
observations. *Annals of Statistics*, 17(3), 1217-1241.
"""

from __future__ import annotations

import functools
import math
import warnings
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass, field
from typing import Any, Literal

import numpy as np
import pandas as pd
from numpy.typing import NDArray

from nowcastbox._logging import get_logger
from nowcastbox.core.data import MixedFrequencyData, StandardizationStats
from nowcastbox.core.exceptions import (
    ConvergenceWarning,
    NowcastBoxWarning,
    NowcastDataError,
)
from nowcastbox.core.frequency import base_to_native, is_fixed_ratio, is_period_end
from nowcastbox.core.results import NowcastResults
from nowcastbox.models.em import MixedFreqDFM, MixedFreqDFMResults
from nowcastbox.models.two_step import TwoStepDFM, TwoStepResults
from nowcastbox.statespace import StateSpace, kalman_smoother, simulate_state_space

__all__ = [
    "BOOTSTRAP_METHODS",
    "BootstrapNowcasts",
    "block_bootstrap_panel",
    "bootstrap_nowcasts",
    "simulate_from_results",
]

logger = get_logger(__name__)

FloatArray = NDArray[np.float64]
RandomState = int | np.random.Generator | np.random.SeedSequence | None
BootstrapMethod = Literal["auto", "parametric", "block"]

BOOTSTRAP_METHODS: tuple[str, ...] = ("auto", "parametric", "block")
"""Accepted values of ``method``."""

_REFIT_ERRORS: tuple[type[BaseException], ...] = (
    NowcastDataError,
    ValueError,
    np.linalg.LinAlgError,
    FloatingPointError,
    ZeroDivisionError,
)


# ====================================================================== results
@dataclass(frozen=True, eq=False)
class BootstrapNowcasts:
    """Nowcasts re-computed with bootstrapped parameters.

    Parameters
    ----------
    means : pandas.DataFrame
        Point nowcasts, one row per successful replication, one column per target
        period.
    stds : pandas.DataFrame
        Smoothing standard deviations of those nowcasts (same shape).
    method : str
        ``"parametric"`` or ``"block"``.
    n_boot : int
        Number of requested replications.
    failures : list of str
        Error messages of the replications whose re-estimation failed.
    n_convergence_warnings : int
        Number of replications whose re-estimation emitted a ``ConvergenceWarning``.
    info : dict
        Extra information (``block_length`` ...).

    Examples
    --------
    >>> from nowcastbox.models import TwoStepDFM
    >>> from nowcastbox.models.two_step import simulate_two_step_example
    >>> from nowcastbox.density import bootstrap_nowcasts
    >>> res = TwoStepDFM(n_factors=1).fit(simulate_two_step_example(random_state=0), "gdp")
    >>> boot = bootstrap_nowcasts(res, n_boot=5, random_state=1)
    >>> boot.means.shape, boot.n_failed
    ((5, 2), 0)
    """

    means: pd.DataFrame
    stds: pd.DataFrame
    method: str
    n_boot: int
    failures: list[str] = field(default_factory=list)
    n_convergence_warnings: int = 0
    info: dict[str, Any] = field(default_factory=dict)

    @property
    def n_success(self) -> int:
        """Number of successful replications."""
        return len(self.means)

    @property
    def n_failed(self) -> int:
        """Number of failed replications."""
        return len(self.failures)

    @property
    def parameter_variance(self) -> pd.Series:
        """Variance of the bootstrapped nowcasts (``ddof=0``) per period."""
        return self.means.var(axis=0, ddof=0).rename("parameter")

    @property
    def filtering_variance(self) -> pd.Series:
        """Average smoothing variance across replications per period."""
        return (self.stds**2).mean(axis=0).rename("filtering")


# ====================================================================== seeds / parallel
def _child_seeds(random_state: RandomState, n: int) -> list[np.random.SeedSequence]:
    """Independent child seed sequences (reproducible, independent of ``n_jobs``)."""
    if isinstance(random_state, np.random.SeedSequence):
        root = random_state
    elif isinstance(random_state, np.random.Generator):
        root = np.random.SeedSequence(int(random_state.integers(0, 2**63 - 1)))
    else:
        root = np.random.SeedSequence(random_state)
    return root.spawn(n)


def _run_parallel(
    task: Callable[[np.random.SeedSequence], Any],
    seeds: Sequence[np.random.SeedSequence],
    n_jobs: int | None,
) -> list[Any]:
    """Run ``task`` over ``seeds`` sequentially or with joblib."""
    if n_jobs is None or n_jobs == 1:
        return [task(s) for s in seeds]
    try:
        from joblib import Parallel, delayed
    except ImportError as exc:  # pragma: no cover - joblib is installed with scikit-learn
        raise ImportError("n_jobs != 1 requires joblib (pip install joblib).") from exc
    return list(Parallel(n_jobs=n_jobs)(delayed(task)(s) for s in seeds))


# ====================================================================== simulation
def _require_fields(results: NowcastResults) -> tuple[MixedFrequencyData, StandardizationStats]:
    if results.data is None or results.standardization is None:
        raise NowcastDataError(
            "The results must contain the estimation data and standardisation statistics."
        )
    return results.data, results.standardization


def _parametric_supported(results: NowcastResults) -> bool:
    """Whether :func:`simulate_from_results` can simulate from ``results``."""
    if isinstance(results, MixedFreqDFMResults):
        return results.state_space is not None and results.state_layout is not None
    if isinstance(results, TwoStepResults) and results.data is not None:
        base = results.data.base_frequency
        target_is_base = results.data.metadata[results.target].frequency == base
        return results.state_space is not None and (
            results.aggregate == "factors" or target_is_base or results.model_data is not None
        )
    return False


def _simulate_two_step(results: TwoStepResults, rng: np.random.Generator) -> MixedFrequencyData:
    data, stats = _require_fields(results)
    if results.is_filtered and results.model_data is not None:
        # aggregate="variables": the state space describes the filtered predictors, so
        # the simulated panel is a *filtered* panel (refit with prefiltered=True).
        data = results.model_data
    ssm, bridge, loadings = results.state_space, results.bridge, results.loadings
    weights = results.aggregation_weights
    assert ssm is not None  # noqa: S101
    assert bridge is not None  # noqa: S101
    assert loadings is not None  # noqa: S101
    assert weights is not None  # noqa: S101
    state_cols = [str(c) for c in loadings.index]
    r = int(loadings.shape[1])
    obs, alpha = simulate_state_space(ssm, data.n_periods, random_state=rng)
    x = stats.inverse_transform(pd.DataFrame(obs, index=data.index, columns=state_cols))
    frame = data.to_frame()
    mask = data.observation_mask()
    for col in state_cols:
        frame[col] = x[col].where(mask[col])
    fbar = sum(w * alpha[:, j * r : (j + 1) * r] for j, w in enumerate(weights))
    coef = bridge.params.to_numpy(dtype=float)
    const, beta = (coef[0], coef[1:]) if bridge.add_constant else (0.0, coef)
    y = const + np.asarray(fbar) @ beta + bridge.sigma * rng.standard_normal(data.n_periods)
    frame[results.target] = pd.Series(y, index=data.index).where(mask[results.target])
    return data.with_data(frame)


def _simulate_em(results: MixedFreqDFMResults, rng: np.random.Generator) -> MixedFrequencyData:
    data, stats = _require_fields(results)
    ssm, layout = results.state_space, results.state_layout
    assert ssm is not None  # noqa: S101
    assert layout is not None  # noqa: S101
    series = list(layout.series)
    if layout.is_time_varying:  # calendar aggregation: model for the estimation grid
        ssm = results.state_space_model(data.n_periods)[0]
    obs, _ = simulate_state_space(ssm, data.n_periods, random_state=rng)
    sim = stats.inverse_transform(pd.DataFrame(obs, index=data.index, columns=series))
    return data.with_data(sim.where(data.observation_mask()[series]))


def simulate_from_results(
    results: NowcastResults, *, random_state: RandomState = None
) -> MixedFrequencyData:
    r"""Simulate a panel from a fitted model (parametric bootstrap data-generating process).

    The panel has the grid, metadata and missing-data pattern of the estimation data;
    the values are drawn from the fitted state-space model (in original units). For
    :class:`~nowcastbox.models.TwoStepDFM` the target is generated by the bridge
    equation on the simulated aggregated factors.

    Parameters
    ----------
    results : TwoStepResults or MixedFreqDFMResults
        Fitted results. With ``TwoStepDFM(aggregate="variables")`` the state space
        describes the *filtered* predictors, so the simulated panel is the filtered
        panel (the grid and pattern of ``results.model_data``), to be refitted with
        ``fit(..., prefiltered=True)``. Calendar (weekly/daily) EM models are
        simulated with their time-varying observation equation.
    random_state : int, numpy.random.Generator, SeedSequence or None
        Seed or generator.

    Returns
    -------
    MixedFrequencyData
        Simulated panel.

    Raises
    ------
    NotImplementedError
        For unsupported results (other models, or two-step results without the state
        space or the filtered panel).
    NowcastDataError
        If the results lack the estimation data.

    Examples
    --------
    >>> from nowcastbox.models import TwoStepDFM
    >>> from nowcastbox.models.two_step import simulate_two_step_example
    >>> from nowcastbox.density import simulate_from_results
    >>> data = simulate_two_step_example(random_state=0)
    >>> res = TwoStepDFM(n_factors=1).fit(data, "gdp")
    >>> sim = simulate_from_results(res, random_state=1)
    >>> sim.shape == data.shape, bool(sim.observation_mask().equals(data.observation_mask()))
    (True, True)
    """
    rng = np.random.default_rng(random_state)
    if not _parametric_supported(results):
        raise NotImplementedError(
            "Parametric simulation is available for MixedFreqDFM results and TwoStepDFM "
            "results with their state space (and, for aggregate='variables', the filtered "
            "panel model_data); use method='block' otherwise."
        )
    if isinstance(results, MixedFreqDFMResults):
        return _simulate_em(results, rng)
    assert isinstance(results, TwoStepResults)  # noqa: S101
    return _simulate_two_step(results, rng)


def _check_block_frequencies(data: MixedFrequencyData, target: str) -> int:
    target_freq = data.metadata[target].frequency
    if not is_fixed_ratio(data.base_frequency, target_freq):
        raise NowcastDataError(
            f"Block bootstrap needs a fixed number of {data.base_frequency.label} periods per "
            f"{target_freq.label} target period (calendar grids have 4-5 weeks per month, "
            "12-14 per quarter); use method='parametric'."
        )
    ratio = data.frequency_ratio(target)
    bad = [c for c in data.columns if ratio % data.frequency_ratio(c) != 0]
    if bad:
        raise NowcastDataError(
            f"Block bootstrap needs every series to be observed at least as often as the "
            f"target; {bad} are not."
        )
    return ratio


def block_bootstrap_panel(
    data: MixedFrequencyData,
    target: str,
    *,
    block_length: int | None = None,
    random_state: RandomState = None,
) -> MixedFrequencyData:
    r"""Moving-block bootstrap of a mixed-frequency panel by whole target periods.

    The base periods are grouped into units of one target period (e.g. the three
    months of a quarter, ending at the target's storage slot). Blocks of
    ``block_length`` consecutive units are drawn with replacement (Künsch, 1989) and
    concatenated, so the storage convention of lower-frequency series is preserved.
    Base periods before the first complete unit and after the last one (a partially
    observed current period) are kept unchanged.

    Parameters
    ----------
    data : MixedFrequencyData
        Panel (stationary transformations).
    target : str
        Series defining the units.
    block_length : int, optional
        Block length in target periods (default :math:`\lceil U^{1/3} \rceil`, with
        :math:`U` the number of complete units).
    random_state : int, numpy.random.Generator, SeedSequence or None
        Seed or generator.

    Returns
    -------
    MixedFrequencyData
        Resampled panel with the original grid and metadata.

    Raises
    ------
    NowcastDataError
        If there are fewer than two complete units or a series is observed less often
        than the target.
    ValueError
        If ``block_length`` is not a positive integer.

    Examples
    --------
    >>> from nowcastbox.models.two_step import simulate_two_step_example
    >>> from nowcastbox.density import block_bootstrap_panel
    >>> data = simulate_two_step_example(random_state=0)
    >>> boot = block_bootstrap_panel(data, "gdp", block_length=4, random_state=0)
    >>> boot.shape == data.shape
    True
    """
    ratio = _check_block_frequencies(data, target)
    slots = np.flatnonzero(data.slot_mask()[target].to_numpy())
    starts = slots[slots - ratio + 1 >= 0] - ratio + 1
    n_units = int(starts.size)
    if n_units < 2:
        raise NowcastDataError("Block bootstrap needs at least two complete target periods.")
    if block_length is None:
        length = max(1, math.ceil(n_units ** (1.0 / 3.0)))
    elif isinstance(block_length, bool) or not isinstance(block_length, int | np.integer):
        raise ValueError(f"block_length must be a positive integer, got {block_length!r}.")
    else:
        length = int(block_length)
    if length < 1:
        raise ValueError(f"block_length must be a positive integer, got {block_length!r}.")
    length = min(length, n_units)
    rng = np.random.default_rng(random_state)
    n_blocks = math.ceil(n_units / length)
    first = rng.integers(0, n_units - length + 1, size=n_blocks)
    order = (first[:, None] + np.arange(length)[None, :]).reshape(-1)[:n_units]
    values = data.values
    out = values.copy()
    offsets = np.arange(ratio)
    out[starts[0] + np.arange(n_units * ratio)] = values[(starts[order][:, None] + offsets).ravel()]
    frame = pd.DataFrame(out, index=data.index, columns=data.columns)
    return data.with_data(frame)


# ====================================================================== refit
def _em_target_moments(
    model: StateSpace,
    stats: StandardizationStats,
    series: Sequence[str],
    data: MixedFrequencyData,
    grid: pd.PeriodIndex,
    target: str,
    method: str,
) -> tuple[pd.Series, pd.Series]:
    r"""Smoothed target and its standard deviation :math:`\sqrt{Z_{t,j} P_t Z_{t,j}' + H_{t,jj}}`.

    ``model`` must cover ``grid`` (time-varying observation equations of calendar
    aggregations are indexed by period).
    """
    frame = data.to_frame()[list(series)].reindex(grid)
    values = stats.transform(frame).to_numpy(dtype=np.float64)
    sm = kalman_smoother(model, values, method=method)  # type: ignore[arg-type]
    j = list(series).index(target)
    freq = data.metadata[target].frequency
    slots = is_period_end(grid, freq)
    native = base_to_native(grid[slots], freq)
    periods = model.period_index(len(grid))[slots]
    z = model.design_store[periods, j, :]
    variance = np.einsum("tij,ti,tj->t", sm.smoothed_state_cov[slots], z, z)
    variance = np.maximum(variance + model.obs_cov_diagonal_store[periods, j], 0.0)
    signal = sm.smoothed_signal()[slots, j]
    mean = pd.Series(stats.inverse_series(signal, target), index=native)
    std = pd.Series(stats.inverse_series(np.sqrt(variance), target, scale_only=True), index=native)
    return mean, std


def _refit_two_step(
    results: TwoStepResults,
    panel: MixedFrequencyData,
    params: Mapping[str, Any],
    prefiltered: bool = False,
) -> tuple[pd.Series, pd.Series]:
    data, _ = _require_fields(results)
    estimator = TwoStepDFM(**params)
    # A parametric panel of aggregate="variables" is already filtered
    # (``prefiltered=True``); the update on the raw data re-applies the fitted filters.
    estimator.fit(panel, results.target, prefiltered=prefiltered)
    updated = estimator.update(data)
    return updated.estimate, updated.nowcast["std"]


def _refit_em(
    results: MixedFreqDFMResults, panel: MixedFrequencyData, params: Mapping[str, Any]
) -> tuple[pd.Series, pd.Series]:
    data, _ = _require_fields(results)
    assert results.grid is not None  # noqa: S101
    estimator = MixedFreqDFM(**params)
    fitted = estimator.fit(panel, results.target, horizon=int(results.info.get("horizon", 0)))
    assert isinstance(fitted, MixedFreqDFMResults)  # noqa: S101
    assert fitted.state_space is not None  # noqa: S101
    assert fitted.state_layout is not None  # noqa: S101
    assert fitted.standardization is not None  # noqa: S101
    return _em_target_moments(
        fitted.state_space_model(len(results.grid))[0],
        fitted.standardization,
        fitted.state_layout.series,
        data,
        results.grid,
        results.target,
        fitted.filter_method,
    )


@dataclass(frozen=True)
class _Replication:
    """Inputs of one bootstrap replication (picklable for joblib)."""

    results: NowcastResults
    method: str
    params: dict[str, Any]
    periods: pd.PeriodIndex
    block_length: int | None


def _draw_panel(spec: _Replication, rng: np.random.Generator) -> MixedFrequencyData:
    if spec.method == "parametric":
        return simulate_from_results(spec.results, random_state=rng)
    data, _ = _require_fields(spec.results)
    return block_bootstrap_panel(
        data, spec.results.target, block_length=spec.block_length, random_state=rng
    )


def _replicate(
    seed: np.random.SeedSequence, spec: _Replication
) -> tuple[FloatArray, FloatArray, bool] | str:
    """One replication: draw a panel, refit, nowcast the original data."""
    rng = np.random.default_rng(seed)
    results = spec.results
    with warnings.catch_warnings(record=True) as caught:
        warnings.simplefilter("always", NowcastBoxWarning)
        try:
            panel = _draw_panel(spec, rng)
            if isinstance(results, MixedFreqDFMResults):
                mean, std = _refit_em(results, panel, spec.params)
            else:
                assert isinstance(results, TwoStepResults)  # noqa: S101
                prefiltered = spec.method == "parametric" and results.is_filtered
                mean, std = _refit_two_step(results, panel, spec.params, prefiltered)
        except _REFIT_ERRORS as exc:
            return f"{type(exc).__name__}: {exc}"
    m = mean.reindex(spec.periods).to_numpy(dtype=np.float64)
    s = std.reindex(spec.periods).to_numpy(dtype=np.float64)
    if not (np.isfinite(m).all() and np.isfinite(s).all() and (s > 0).all()):
        return "Non-finite nowcast or standard deviation."
    not_converged = any(issubclass(w.category, ConvergenceWarning) for w in caught)
    return m, s, not_converged


def _refit_params(
    results: NowcastResults, overrides: Mapping[str, Any] | None, warm_start: bool
) -> dict[str, Any]:
    params = dict(results.model_params)
    if isinstance(results, MixedFreqDFMResults) and warm_start:
        params["init"] = results
    params.update(overrides or {})
    return params


def _resolve_method(results: NowcastResults, method: str) -> str:
    if method not in BOOTSTRAP_METHODS:
        raise ValueError(f"method must be one of {BOOTSTRAP_METHODS}, got {method!r}.")
    if method == "auto":
        return "parametric" if _parametric_supported(results) else "block"
    if method == "parametric" and not _parametric_supported(results):
        raise NotImplementedError(
            "Parametric bootstrap is not available for these results (TwoStepDFM results "
            "without the state space or the filtered panel); use method='block'."
        )
    return method


def _check_n_boot(n_boot: object) -> int:
    if isinstance(n_boot, bool) or not isinstance(n_boot, int | np.integer) or n_boot < 1:
        raise ValueError(f"n_boot must be a positive integer, got {n_boot!r}.")
    return int(n_boot)


def default_periods(results: NowcastResults) -> pd.PeriodIndex:
    """Target periods with an out-of-sample estimate and a finite standard deviation.

    Parameters
    ----------
    results : NowcastResults
        Fitted results whose ``nowcast`` frame has a ``std`` column.

    Returns
    -------
    pandas.PeriodIndex
        Backcast, nowcast and forecast periods.

    Raises
    ------
    NowcastDataError
        If the results have no ``std`` column or no such period.

    Examples
    --------
    >>> from nowcastbox.models import TwoStepDFM
    >>> from nowcastbox.models.two_step import simulate_two_step_example
    >>> from nowcastbox.density.bootstrap import default_periods
    >>> res = TwoStepDFM(n_factors=1).fit(simulate_two_step_example(random_state=0), "gdp")
    >>> [str(p) for p in default_periods(res)]
    ['2014Q4', '2015Q1']
    """
    frame = results.nowcast
    if "std" not in frame.columns:
        raise NowcastDataError(
            f"The nowcast of {results.model_name or 'these results'} has no 'std' column; "
            "no predictive distribution is available."
        )
    std = frame["std"]
    ok = frame["out_of_sample"].notna() & std.notna() & (std > 0)
    index = frame.index[ok.to_numpy()]
    if len(index) == 0:
        raise NowcastDataError("No out-of-sample period with a standard deviation.")
    assert isinstance(index, pd.PeriodIndex)  # noqa: S101
    return index


def bootstrap_nowcasts(
    results: NowcastResults,
    n_boot: int = 199,
    *,
    method: BootstrapMethod = "auto",
    periods: pd.PeriodIndex | None = None,
    random_state: RandomState = None,
    n_jobs: int | None = None,
    refit_params: Mapping[str, Any] | None = None,
    warm_start: bool = True,
    block_length: int | None = None,
) -> BootstrapNowcasts:
    """Re-estimate the model on bootstrap panels and nowcast the original data.

    Parameters
    ----------
    results : TwoStepResults or MixedFreqDFMResults
        Fitted results (with the estimation data).
    n_boot : int, default 199
        Number of bootstrap replications.
    method : {"auto", "parametric", "block"}, default "auto"
        ``"parametric"``: simulate from the fitted state space (see
        :func:`simulate_from_results`); ``"block"``: moving-block bootstrap of the
        panel by target periods (:func:`block_bootstrap_panel`); ``"auto"``:
        parametric when available, block otherwise.
    periods : pandas.PeriodIndex, optional
        Target periods to record (default: out-of-sample periods with a standard
        deviation, see :func:`default_periods`).
    random_state : int, numpy.random.Generator, SeedSequence or None
        Seed; replications use independent child seeds, so the result does not depend
        on ``n_jobs``.
    n_jobs : int, optional
        Number of joblib workers (``None``/``1``: sequential, ``-1``: all cores).
    refit_params : mapping, optional
        Estimator hyper-parameters overriding those of the original fit (e.g.
        ``{"max_iter": 50}`` to speed up the EM).
    warm_start : bool, default True
        Start the EM of each replication from the original estimates.
    block_length : int, optional
        Block length (in target periods) of the block bootstrap.

    Returns
    -------
    BootstrapNowcasts
        Bootstrapped nowcasts and standard deviations.

    Raises
    ------
    TypeError
        If the results are not from ``TwoStepDFM`` or ``MixedFreqDFM``.
    ValueError
        On invalid ``n_boot`` or ``method``.
    NotImplementedError
        For ``method="parametric"`` with two-step results that do not store the state
        space (or, for ``aggregate="variables"``, the filtered panel).
    NowcastDataError
        If every replication fails, or for ``method="block"`` on a calendar grid
        (weekly/daily base with a variable number of periods per target period).

    Warns
    -----
    ConvergenceWarning
        If some replications failed (they are dropped).

    Examples
    --------
    >>> from nowcastbox.models import TwoStepDFM
    >>> from nowcastbox.models.two_step import simulate_two_step_example
    >>> from nowcastbox.density import bootstrap_nowcasts
    >>> res = TwoStepDFM(n_factors=1).fit(simulate_two_step_example(random_state=0), "gdp")
    >>> boot = bootstrap_nowcasts(res, n_boot=10, random_state=0)
    >>> bool((boot.parameter_variance > 0).all())
    True
    """
    if not isinstance(results, TwoStepResults | MixedFreqDFMResults):
        raise TypeError(
            "bootstrap_nowcasts supports TwoStepDFM and MixedFreqDFM results, got "
            f"{type(results).__name__}."
        )
    n = _check_n_boot(n_boot)
    resolved = _resolve_method(results, method)
    _require_fields(results)
    index = default_periods(results) if periods is None else periods
    spec = _Replication(
        results=results,
        method=resolved,
        params=_refit_params(results, refit_params, warm_start),
        periods=index,
        block_length=block_length,
    )
    if resolved == "block":
        assert results.data is not None  # noqa: S101
        block_bootstrap_panel(results.data, results.target, block_length=block_length)
    outputs = _run_parallel(
        functools.partial(_replicate, spec=spec), _child_seeds(random_state, n), n_jobs
    )
    return _collect(outputs, index, resolved, n, block_length)


def _collect(
    outputs: list[Any], index: pd.PeriodIndex, method: str, n_boot: int, block_length: int | None
) -> BootstrapNowcasts:
    failures = [o for o in outputs if isinstance(o, str)]
    good = [o for o in outputs if not isinstance(o, str)]
    if not good:
        raise NowcastDataError(
            f"All {n_boot} bootstrap replications failed; first error: {failures[0]}"
        )
    if failures:
        warnings.warn(
            f"{len(failures)} of {n_boot} bootstrap replications failed and were dropped "
            f"(first error: {failures[0]}).",
            ConvergenceWarning,
            stacklevel=3,
        )
    rows = pd.RangeIndex(len(good), name="replication")
    means = pd.DataFrame(np.vstack([g[0] for g in good]), index=rows, columns=index)
    stds = pd.DataFrame(np.vstack([g[1] for g in good]), index=rows, columns=index)
    logger.debug("bootstrap: %d/%d replications succeeded", len(good), n_boot)
    return BootstrapNowcasts(
        means=means,
        stds=stds,
        method=method,
        n_boot=n_boot,
        failures=failures,
        n_convergence_warnings=sum(bool(g[2]) for g in good),
        info={"block_length": block_length},
    )
